FROM mcr.microsoft.com/devcontainers/base:noble

LABEL name="datahut" \
    maintainer="datahut" \
    description="A data science circus environment for datahut projects" \
    version="1.0"

